-- Tạo bảng để lưu trữ từ vựng
CREATE TABLE vocabulary (
    id INT AUTO_INCREMENT PRIMARY KEY,
    word VARCHAR(100),
    definition TEXT,
    topic VARCHAR(50)
);

INSERT INTO vocabulary (word, definition, topic) VALUES 
('Elephant', 'A large herbivorous mammal with a long trunk, large ears, and tusks.', 'Animals'),
('Lion', 'A large carnivorous feline mammal of Africa and NW India, with a short tawny coat, a tufted tail, and, in the male, a heavy mane.', 'Animals'),
('Giraffe', 'A large African mammal with a very long neck and forelegs, having a coat patterned with brown patches separated by lighter lines.', 'Animals'),
('Penguin', 'A flightless bird that lives in the southern hemisphere, especially in Antarctica, and typically breeds on rocky shores or ice cliffs.', 'Animals'),
('Kangaroo', 'A large marsupial with a distinctive pouch for carrying young, native to Australia.', 'Animals'),
('Tiger', 'A large predatory cat with a coat typically yellowish-brown with black stripes.', 'Animals'),
('Zebra', 'A large wild animal that looks like a horse and has black and white stripes.', 'Animals'),
('Hippopotamus', 'A large thick-skinned semiaquatic African mammal, with massive jaws and large tusks.', 'Animals'),
('Koala', 'An Australian arboreal marsupial that has thick gray fur and feeds on eucalyptus leaves.', 'Animals'),
('Panda', 'A large bear-like mammal with characteristic black and white markings, native to certain mountain forests of central and western China.', 'Animals'),
('Crocodile', 'A large predatory reptile with a tough skin, long body, and tail, and a mouthful of sharp teeth.', 'Animals'),
('Gorilla', 'The largest of the anthropoid apes, native to the forests of central Africa.', 'Animals'),
('Pizza', 'A dish of Italian origin consisting of a flat, round base of dough topped with tomatoes, cheese, and various other ingredients.', 'Food'),
('Sushi', 'A Japanese dish consisting of small balls or rolls of vinegar-flavored cold rice served with a garnish of raw fish, vegetables, or egg.', 'Food'),
('Burger', 'A flat round cake of minced beef or other savory ingredients, typically cooked and served in a bread roll.', 'Food'),
('Pasta', 'Italian dish made from dough of flour, water, and sometimes eggs, cut into thin strips or other shapes, and cooked in boiling water.', 'Food'),
('Taco', 'A Mexican dish consisting of a folded or rolled tortilla filled with various mixtures, typically including seasoned meat, beans, lettuce, and cheese.', 'Food'),
('Sushi', 'A Japanese dish consisting of small balls or rolls of vinegar-flavored cold rice served with a garnish of raw fish, vegetables, or egg.', 'Food'),
('Pancake', 'A thin, flat cake of batter, usually fried and turned in a pan, and eaten hot with syrup or other sweet toppings.', 'Food'),
('Sushi', 'A Japanese dish consisting of small balls or rolls of vinegar-flavored cold rice served with a garnish of raw fish, vegetables, or egg.', 'Food'),
('Curry', 'A dish of meat, vegetables, etc., cooked in an Indian-style sauce of strong spices and typically served with rice.', 'Food'),
('Dumpling', 'A small savory ball of dough (usually made with flour) and sometimes suet enclosing a filling and cooked by boiling or steaming.', 'Food'),
('Kebab', 'Pieces of meat, fish, or vegetables roasted or grilled on a skewer or spit, especially a Middle Eastern dish.', 'Food'),
('Tiramisu', 'An Italian dessert consisting of layers of sponge cake soaked in coffee and brandy or liqueur with powdered chocolate and mascarpone cheese.', 'Food'),
('Car', 'A road vehicle, typically with four wheels, powered by an internal combustion engine and able to carry a small number of people.', 'Transportation'),
('Bicycle', 'A vehicle with two wheels held in a frame one behind the other, propelled by pedals and steered with handlebars attached to the front wheel.', 'Transportation'),
('Train', 'A connected series of railroad cars propelled along a track by a locomotive or by integral motors.', 'Transportation'),
('Airplane', 'A powered flying vehicle with fixed wings and a weight greater than that of the air it displaces.', 'Transportation'),
('Boat', 'A small vessel propelled on water by oars, sails, or an engine.', 'Transportation'),
('Motorcycle', 'A two-wheeled vehicle that is powered by a motor and has no pedals.', 'Transportation'),
('Tram', 'A vehicle that runs on a track laid in a public road and is used to carry passengers, especially in urban areas.', 'Transportation'),
('Jet ski', 'A small, jet-propelled vehicle that skims across the surface of water and is ridden in a similar way to a motorcycle.', 'Transportation'),
('Spaceship', 'A manned spacecraft designed for travel or transportation in outer space.', 'Transportation'),
('RV (Recreational Vehicle)', 'A motor vehicle equipped with living quarters and amenities for accommodation, typically used for leisure travel.', 'Transportation'),
('Sailboat', 'A boat propelled by sails, used especially for recreation or racing.', 'Transportation'),
('Submarine', 'A watercraft capable of independent operation underwater.', 'Transportation'),
('Red', 'The color of blood or a ripe tomato.', 'Colors'),
('Blue', 'The color of the sky on a clear day.', 'Colors'),
('Yellow', 'The color of a lemon or the yolk of an egg.', 'Colors'),
('Green', 'The color of grass or leaves.', 'Colors'),
('Purple', 'A color intermediate between red and blue.', 'Colors'),
('Orange', 'A color between red and yellow in the spectrum.', 'Colors'),
('Pink', 'A color varying from light crimson to pale reddish purple.', 'Colors'),
('Black', 'The darkest color, the result of the absence of or complete absorption of light.', 'Colors'),
('White', 'The color of milk or snow.', 'Colors'),
('Brown', 'The color of dark wood or rich soil.', 'Colors'),
('Grey', 'The color intermediate between black and white.', 'Colors'),
('Turquoise', 'A greenish-blue color.', 'Colors'),
('Football', 'A game played between two teams of eleven players with a spherical ball.', 'Sports'),
('Basketball', 'A game played between two teams of five players each, typically indoors, with the objective of scoring points by throwing a ball through a hoop.', 'Sports'),
('Tennis', 'A racket sport played individually against a single opponent or between two teams of two players each.', 'Sports'),
('Soccer', 'A game played by two teams of eleven players with a round ball that may not be touched with the hands or arms during play.', 'Sports'),
('Golf', 'A game played on a large open-air course, in which a small hard ball is struck with a club into a series of small holes in the ground.', 'Sports'),
('Baseball', 'A game played with a bat and ball between two teams of nine players each.', 'Sports'),
('Swimming', 'The sport or activity of propelling oneself through water using the limbs.', 'Sports'),
('Athletics', 'Physical sports and games of any kind.', 'Sports'),
('Volleyball', 'A game for two teams, usually of six players, in which a large ball is hit by hand over a high net.', 'Sports'),
('Hockey', 'A game played on a field or rink with curved sticks and a ball or puck.', 'Sports'),
('Boxing', 'A sport in which two people fight while wearing padded gloves.', 'Sports'),
('Rugby', 'A team game played with an oval ball that may be kicked, carried, and passed from hand to hand.', 'Sports'),
('United States', 'A country primarily located in North America, consisting of 50 states.', 'Countries'),
('France', 'A country in Western Europe known for its culture, art, and cuisine.', 'Countries'),
('China', 'A country in East Asia known for its rich history and culture.', 'Countries'),
('Brazil', 'The largest country in South America, known for its biodiversity and vibrant culture.', 'Countries'),
('India', 'A country in South Asia known for its diverse culture, history, and spirituality.', 'Countries'),
('Russia', 'The largest country in the world, spanning Eastern Europe and Northern Asia.', 'Countries'),
('Japan', 'An island country in East Asia known for its technological innovation and traditional culture.', 'Countries'),
('Germany', 'A country in Central Europe known for its contributions to art, science, and philosophy.', 'Countries'),
('Australia', 'A country and continent surrounded by the Indian and Pacific oceans.', 'Countries'),
('Canada', 'A country in North America known for its natural beauty and multicultural society.', 'Countries'),
('Mexico', 'A country in North America known for its rich history, cuisine, and traditions.', 'Countries'),
('South Africa', 'A country at the southernmost tip of the African continent known for its diverse cultures and wildlife.', 'Countries'),
('Mathematics', 'The study of numbers, quantity, structure, and change.', 'Subjects'),
('History', 'The study of past events, particularly in human affairs.', 'Subjects'),
('Biology', 'The study of living organisms and their interactions with each other and their environments.', 'Subjects'),
('Chemistry', 'The study of the composition, structure, properties, and reactions of matter.', 'Subjects'),
('Physics', 'The study of matter, energy, and the fundamental forces of nature.', 'Subjects'),
('Literature', 'The study of written works, including fiction, poetry, drama, and essays.', 'Subjects'),
('Geography', 'The study of the Earth’s landscapes, environments, and the relationships between people and their environments.', 'Subjects'),
('Art', 'The study and creation of visual works of expression.', 'Subjects'),
('Computer Science', 'The study of computers and computational systems.', 'Subjects'),
('Economics', 'The study of the production, distribution, and consumption of goods and services.', 'Subjects'),
('Psychology', 'The study of the human mind and behavior.', 'Subjects'),
('Sociology', 'The study of society, social relationships, and institutions.', 'Subjects'),
('Guitar', 'A stringed musical instrument played by plucking or strumming the strings.', 'Musical Instruments'),
('Piano', 'A large keyboard instrument with keys used for playing melodies and harmonies.', 'Musical Instruments'),
('Violin', 'A stringed instrument played with a bow, held horizontally and played on the strings.', 'Musical Instruments'),
('Drums', 'A percussion instrument played by striking with the hands or with sticks or brushes.', 'Musical Instruments'),
('Flute', 'A wind instrument consisting of a tube with holes that are stopped by the fingers or keys.', 'Musical Instruments'),
('Trumpet', 'A brass musical instrument with a flared bell and a bright, penetrating tone.', 'Musical Instruments'),
('Saxophone', 'A woodwind instrument played by blowing into a single reed mouthpiece.', 'Musical Instruments'),
('Cello', 'A large stringed instrument played with a bow, held upright between the legs.', 'Musical Instruments'),
('Harp', 'A large, stringed musical instrument played by plucking the strings with fingers.', 'Musical Instruments'),
('Clarinet', 'A woodwind instrument with a single-reed mouthpiece, a cylindrical tube, and holes stopped by keys.', 'Musical Instruments'),
('Tambourine', 'A percussion instrument consisting of a small drumhead with metal jingles in the rim.', 'Musical Instruments'),
('Accordion', 'A portable musical instrument with a keyboard and a set of bellows, played by pressing keys.', 'Musical Instruments'),
('Rainbow', 'A meteorological phenomenon that is caused by reflection, refraction, and dispersion of light in water droplets.', 'Natural Phenomena'),
('Tornado', 'A violently rotating column of air extending from a thunderstorm to the ground.', 'Natural Phenomena'),
('Earthquake', 'The shaking of the surface of the Earth resulting from a sudden release of energy in the Earth’s lithosphere.', 'Natural Phenomena'),
('Aurora', 'A natural light display predominantly seen in high-latitude regions around the Arctic and Antarctic.', 'Natural Phenomena'),
('Volcano', 'A rupture in the Earth’s crust that allows lava, ash, and gases to escape from magma chambers below the surface.', 'Natural Phenomena'),
('Hurricane', 'A tropical cyclone with sustained winds reaching or exceeding 74 mph.', 'Natural Phenomena'),
('Tsunami', 'A series of ocean waves caused by an underwater earthquake, volcanic eruption, or landslide.', 'Natural Phenomena'),
('Solar Eclipse', 'An astronomical event that occurs when the Moon passes between the Sun and Earth.', 'Natural Phenomena'),
('Avalanche', 'A rapid flow of snow down a sloping surface.', 'Natural Phenomena'),
('Fog', 'A thick cloud of tiny water droplets suspended in the atmosphere near the Earth’s surface.', 'Natural Phenomena'),
('Hailstorm', 'A storm characterized by pelting hailstones.', 'Natural Phenomena'),
('Wildfire', 'An uncontrolled fire in an area of combustible vegetation.', 'Natural Phenomena'),
('Chair', 'A seat typically having four legs and a back for one person.', 'Everyday Items'),
('Table', 'A piece of furniture with a flat top and one or more legs.', 'Everyday Items'),
('Plate', 'A flat dish, typically circular and made of ceramic or glass, used for serving food.', 'Everyday Items'),
('Cup', 'A small bowl-shaped container for drinking from, typically having a handle.', 'Everyday Items'),
('Knife', 'A utensil with a cutting edge and a handle used for cutting or as a weapon.', 'Everyday Items'),
('Fork', 'A tool with two or more prongs used for lifting and eating food.', 'Everyday Items'),
('Spoon', 'An eating or cooking utensil with a small shallow bowl and a handle.', 'Everyday Items'),
('Clock', 'A device for measuring and showing time, typically in hours, minutes, and seconds.', 'Everyday Items'),
('Mirror', 'A reflective surface, typically of glass coated with a metal amalgam.', 'Everyday Items'),
('Bottle', 'A rigid container with a neck used for storing liquids.', 'Everyday Items'),
('Key', 'A small piece of shaped metal with incisions for fitting into a lock and opening or closing it.', 'Everyday Items'),
('Phone', 'A device used for transmitting sound, especially speech, to a distant point.', 'Everyday Items');